image: gradle:5.6-jdk12

stages:
  - build
  - validate
  - test
  - deploy

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MYSQL_ROOT_PASSWORD: "password"
  MYSQL_DATABASE: "snake"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

checkStyle:
  stage: validate
  script: gradle checkstyleMain checkstyleTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/

spotBugs:
  stage: validate
  script: gradle spotbugsMain spotbugsTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/

PMD:
  stage: validate
  script: gradle pmdMain pmdTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/

test:
  stage: test
  script:
    gradle check

deploy:
  image: mysql
  stage: deploy
  services:
    - mysql:latest
  script:
    - mysql --host=projects-db.ewi.tudelft.nl --user=pu_Snake1 --password=tHWLSWJqg57E projects_Snake1 < "setup.sql"

